# Generated by Django 3.0.7 on 2020-06-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('book_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='书籍编号')),
                ('book_img_url', models.CharField(default='-1', max_length=50, verbose_name='书籍图片')),
                ('book_introduction', models.CharField(max_length=500, verbose_name='书籍介绍')),
                ('book_hot_rate', models.IntegerField(verbose_name='书籍热度')),
                ('book_name', models.CharField(max_length=50, verbose_name='书籍名称')),
                ('book_word_count', models.IntegerField(verbose_name='字数统计')),
            ],
            options={
                'verbose_name': '书籍信息库',
                'verbose_name_plural': '书籍信息库',
                'db_table': 'df_book',
            },
        ),
    ]
