# Generated by Django 3.0.7 on 2020-06-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_book_statue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='书籍编号'),
        ),
    ]
