# Generated by Django 3.0.7 on 2020-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200628_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('comment_statue', models.IntegerField(default=-1, verbose_name='评论状态')),
            ],
            options={
                'verbose_name': '书籍评论库',
                'verbose_name_plural': '书籍评论库',
                'db_table': 'book_comment',
            },
        ),
    ]
