# Generated by Django 3.0.7 on 2020-06-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_bookcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img_url',
            field=models.URLField(default='-1', verbose_name='书籍图片'),
        ),
    ]
