# Generated by Django 3.0.6 on 2020-06-09 02:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('chapter_id', models.IntegerField(max_length=8, primary_key=True, serialize=False, verbose_name='章节编号')),
                ('text', tinymce.models.HTMLField(blank=True, verbose_name='章节正文')),
                ('book_id', models.IntegerField(max_length=8, verbose_name='所属书籍')),
                ('chapter_img_url', models.CharField(default='-1', max_length=50, verbose_name='章节图片')),
                ('chapter_introduction', models.CharField(max_length=500, verbose_name='章节介绍')),
                ('chapter_hot_rate', models.IntegerField(max_length=10, verbose_name='章节热度')),
                ('chapter_name', models.CharField(max_length=50, verbose_name='章节名称')),
                ('user_id', models.IntegerField(default=-1, max_length=8, verbose_name='作者姓名')),
                ('chapter_word_count', models.IntegerField(max_length=10, verbose_name='字数统计')),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
    ]
