# Generated by Django 3.0.7 on 2020-06-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('star_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='收藏编号')),
                ('book_mark', models.IntegerField(verbose_name='书签位置')),
                ('book', models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='book.Book', verbose_name='书籍编号')),
            ],
            options={
                'verbose_name': '收藏库',
                'verbose_name_plural': '收藏库',
                'db_table': 'df_star',
            },
        ),
    ]
