# Generated by Django 3.0.7 on 2020-06-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('book', '0003_auto_20200610_0145'),
        ('star', '0002_star_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='book_id',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='book.Book', verbose_name='书籍编号'),
        ),
        migrations.AlterField(
            model_name='star',
            name='user_id',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='user.User', verbose_name='用户'),
        ),
    ]
