# Generated by Django 3.0.7 on 2020-06-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0004_auto_20200610_1423'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='star',
            table='star',
        ),
    ]
