# Generated by Django 3.0.7 on 2020-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='star_statue',
            field=models.IntegerField(default=-1, verbose_name='收藏状态'),
        ),
        migrations.AlterField(
            model_name='star',
            name='book_mark',
            field=models.IntegerField(default=0, verbose_name='书签位置'),
        ),
        migrations.AlterField(
            model_name='star',
            name='star_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='收藏编号'),
        ),
    ]
