# Generated by Django 3.0.7 on 2020-06-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_position',
            field=models.IntegerField(default=-1, verbose_name='章节位置'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_statue',
            field=models.IntegerField(default=-1, verbose_name='章节状态'),
        ),
    ]
