# Generated by Django 3.0.7 on 2020-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0002_auto_20200628_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='章节编号'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_position',
            field=models.IntegerField(verbose_name='章节位置'),
        ),
    ]
