# Generated by Django 3.0.7 on 2020-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0003_auto_20200628_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('comment_statue', models.IntegerField(default=-1, verbose_name='评论状态')),
            ],
            options={
                'verbose_name': '章节评论库',
                'verbose_name_plural': '章节评论库',
                'db_table': 'chapter_comment',
            },
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='text',
            new_name='chapter_content',
        ),
    ]
