# Generated by Django 3.0.7 on 2020-06-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0004_auto_20200629_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_img_url',
            field=models.URLField(default='-1', verbose_name='章节图片'),
        ),
    ]
