# Generated by Django 3.0.7 on 2020-06-29 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200629_1610'),
        ('chapter', '0005_auto_20200629_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('tag_statue', models.IntegerField(default=-1, verbose_name='标签状态')),
            ],
            options={
                'verbose_name': '标签库',
                'verbose_name_plural': '标签库',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='TagMassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('tag_hot_rate', models.IntegerField(default=-1, verbose_name='标签热度')),
                ('tag_name', models.CharField(default=-1, max_length=50, verbose_name='标签名称')),
                ('tag_statue', models.IntegerField(default=-1, verbose_name='标签状态')),
            ],
            options={
                'verbose_name': '标签详情库',
                'verbose_name_plural': '标签详情库',
                'db_table': 'tag_massage',
            },
        ),
        migrations.AlterField(
            model_name='chapter',
            name='user_id',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='user.User', verbose_name='作者'),
        ),
    ]
