# Generated by Django 3.0.6 on 2020-06-09 02:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book_id',
            field=models.IntegerField(verbose_name='所属书籍'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_hot_rate',
            field=models.IntegerField(verbose_name='章节热度'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='章节编号'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_word_count',
            field=models.IntegerField(verbose_name='字数统计'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='章节正文'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='user_id',
            field=models.IntegerField(default=-1, verbose_name='作者姓名'),
        ),
    ]
