# Generated by Django 3.0.7 on 2020-06-09 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0002_auto_20200609_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': '章节库', 'verbose_name_plural': '章节库'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 9, 17, 36, 30, 381509, tzinfo=utc), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
