# Generated by Django 3.0.7 on 2020-06-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('FrontPage', '0004_auto_20200610_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='user_id',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='user.User', verbose_name='作者姓名'),
        ),
    ]
