# Generated by Django 3.0.7 on 2020-06-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0006_auto_20200610_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='book_id',
        ),
    ]
